Models/ErrorViewModel.cs
using System;

namespace PruebaTecnicaITOSDanielVillatoro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ArrayOperationsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnicaITOSDanielVillatoro.Controllers
{
    public class ArrayOperationsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/BisiestoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnicaITOSDanielVillatoro.Controllers
{
    public class BisiestoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PruebaTecnicaITOSDanielVillatoro.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnicaITOSDanielVillatoro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OrderListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnicaITOSDanielVillatoro.Controllers
{
    public class OrderListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RestApiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnicaITOSDanielVillatoro.Controllers
{
    public class RestApiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnicaITOSDanielVillatoro.Controllers
{
    public class TableController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/ArrayOperations/Index.cshtml
@{
    Layout = "_Layout";
}
<h3>Arreglos Operaciones</h3>
<div class="text-center">
    <p>
        Generar dos arreglos A y B con 10 valores aleatorios de letras del abecedario y mostrar los
        siguientes resultados:
    </p>

</div>

<div class="row">
    <div class="col-md-2">
        <button class="btn btn-success" onclick="GetList()">Generar <i class="fas fa-check-circle"></i></button>
    </div>
    <div class="col-md-5">
        <h4>Lista A:</h4>
        <ul class="list-group" id="AList">
        </ul>
    </div>
    <div class="col-md-5">
        <h4>Lista B:</h4>
        <ul class="list-group" id="BList">
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <h4>
            Unión: 𝐴⋃𝐵
        </h4>
        <ul class="list-group" id="unionList">
        </ul>
    </div>
    <div class="col-md-3">
        <h4>Intersección 𝐴⋂B</h4>
        <ul class="list-group" id="intersectionList">
        </ul>
    </div>

    <div class="col-md-3">
        <h4>
            Diferencia: 𝐴∆𝐵
        </h4>
        <ul class="list-group" id="differenceList">
        </ul>
    </div>
    <div class="col-md-3">
        <h4>Diferencia Simétrica: 𝐴 − B</h4>
        <ul class="list-group" id="symmetricalDifferenceList">
        </ul>
    </div>
</div>

<script src="~/js/ArrayOperations.js" asp-append-version="true"></script>

Views/Bisiesto/Index.cshtml
@{
    Layout = "_Layout";
}
<h3>Determina Año Bisiesto</h3>
<div class="text-center">
    <p>
        Crear un input donde se ingrese un año y determina si es bisiesto en el calendario gregoriano.
    </p>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="input-group">
            <div class="input-group-prepend">
                <div id="btnGroupAddonYear"><button class="btn-primary btn" onclick="GetResult()">Determinar <i class="fas fa-search"></i></button> </div>
            </div>
            <input type="number" placeholder="Ingrese un año." class="form-control" aria-label="Ingrese un año" aria-describedby="btnGroupAddonYear" id="yearInput" onkeyup="cleanInput()" />
        </div>

    </div>
    <div class="col-md-6">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text bg-success" id="btnGroupAddonRes" style="color:white">Resultado: </div>
            </div>
            <input type="text" class="form-control" aria-label="Resultado" aria-describedby="btnGroupAddonRes" readonly id="resultInput" />
        </div>
    </div>
</div>
<script src="~/js/Bisiesto.js" asp-append-version="true"></script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}


<div class="text-center">
    <h1 class="display-4">Prueba Técnica Daniel Villatoro </h1>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>

Views/OrderList/Index.cshtml
@{
    Layout = "_Layout";
}
<h3>Ordenar Lista</h3>
<div class="text-center">
    <p>
        Generar un arreglo con 20 números aleatorios de 1 a 100 y luego organizarlo de menor a
        mayor sin utilizar la sentencia .sort().
    </p>

</div>

<div class="row">
    <div class="col-md-2">
        <button class="btn btn-success" onclick="GetList()">Generar <i class="fas fa-check-circle"></i></button>
    </div>
    <div class="col-md-3">
        <h4>Lista Desordenada:</h4>
        <ul class="list-group" id="firtsList">

        </ul>
    </div>
    <div class="col-md-3">
        <h4>Lista Ordenada:</h4>
        <ul class="list-group" id="secondList">

        </ul>
    </div>
</div>

<script src="~/js/OrderList.js" asp-append-version="true"></script>

Views/RestApi/Index.cshtml
@{
    Layout = "_Layout";
}
<h3>Rest API</h3>
<div class="text-center">
    <p>
        Se debe realizar una consulta tipo Rest al API de banco de MX del tipo de cambio de los
        últimos 5 días y mostrarlo en una tabla con fecha y tipo de cambio, a través de una página
        html básica.
    </p>

</div>

@*<div class="form-group">*@
<div class="row">
    @*<div class="col-md-3">
        <div class="input-group">
            <div class="input-group-prepend">
                <div id="btnGroupAddonCol" class="input-group-text bg-primary" style="color:white">Columna:  </div>
            </div>
            <input type="number" placeholder="Columna." class="form-control" id="colInput" aria-describedby="btnGroupAddonCol" />
        </div>
    </div>
    <div class="col-md-3">
        <div class="input-group">
            <div class="input-group-prepend">
                <div id="btnGroupAddonRow" class="input-group-text bg-primary" style="color:white">Fila:  </div>
            </div>
            <input type="number" placeholder="Fila." class="form-control" id="rowInput" aria-describedby="btnGroupAddonRow" />
        </div>
    </div>*@

    <div class="col-md-3">
        <button class="btn btn-success" onclick="GetData()">Generar <i class="fas fa-check-circle"></i></button>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover">
        <thead id="theadTable">
            <tr>
                <th scope="col">Fecha</th>
                <th scope="col">Valor</th>
            </tr>
        </thead>
        <tbody id="tbodyTable">
        </tbody>
    </table>
</div>
@*</div>*@

<script src="~/js/RestApi.js" asp-append-version="true"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaTecnicaITOSDanielVillatoro</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Prueba Técnica JS ITOS
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bisiesto" asp-action="Index">Determina Bisiesto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Index">Generar Tabla</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderList" asp-action="Index">Ordenar Lista</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArrayOperations" asp-action="Index">Arreglos Operaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RestApi" asp-action="Index">Rest API</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Prueba Tecnica ITOS Daniel Villatoro
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Table/Index.cshtml
@{
    Layout = "_Layout";
}
<h3>Generar Tabla</h3>
<div class="text-center">
    <p>
        Crear dos input, filas y columnas donde se ingresan estos datos y se genere automáticamente
        una tabla con las dimensiones suministradas
    </p>
</div>

<div class="row">
    <div class="col-md-3">
        <div class="input-group">
            <div class="input-group-prepend">
                <div id="btnGroupAddonCol" class="input-group-text bg-primary" style="color:white">Columna:  </div>
            </div>
            <input type="number" placeholder="Columna." class="form-control" id="colInput" aria-describedby="btnGroupAddonCol" min="0"/>
        </div>
    </div>
    <div class="col-md-3">
        <div class="input-group">
            <div class="input-group-prepend">
                <div id="btnGroupAddonRow" class="input-group-text bg-primary" style="color:white">Fila:  </div>
            </div>
            <input type="number" placeholder="Fila." class="form-control" id="rowInput" aria-describedby="btnGroupAddonRow" min="0"/>
        </div>
    </div>
    <div class="col-md-3">
        <button class="btn btn-success" onclick="GetTable()">Generar <i class="fas fa-check-circle"></i></button>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover">
        <thead id="theadTable">
        </thead>
        <tbody id="tbodyTable">
        </tbody>
    </table>
</div>

<script src="~/js/Table.js" asp-append-version="true"></script>